### ISSUE TITLE
I see <#component> with "any text" doesn't recognize the text

### ISSUE THREAD

**Issue by silvoneymachado** [thiagodp/concordialang#37]
Example: 

```
      Given that I am in the [Lista de tarefas]
      When I fill <#inputtask2> with "test"
        And I click on <#btnAdicionar>
      Then I see "test"
      Then I click on <#btnEdit>
      Then I see <#btnCancelarEdicao>
        And I see <#inputtask2> with "test"
``` 
Console output:
```
 expected element #inputtask2 to include "test"
      + expected - actual

      +test


  Scenario Steps:

  - I.see("test", "#inputtask2") at Test.Scenario (src\__tests__\e2e\tests\task.js:32:7)
  - I.seeElement("#btnCancelarEdicao") at Test.Scenario (src\__tests__\e2e\tests\task.js:31:7)
  - I.click("#btnEdit") at Test.Scenario (src\__tests__\e2e\tests\task.js:30:7)
  - I.see("test") at Test.Scenario (src\__tests__\e2e\tests\task.js:29:7)
  - I.click("#btnAdicionar") at Test.Scenario (src\__tests__\e2e\tests\task.js:28:7)
  - I.fillField("#inputtask2", "test") at Test.Scenario (src\__tests__\e2e\tests\task.js:27:7)
  - I.amOnPage("http://localhost:4200/") at Test.Scenario (src\__tests__\e2e\tests\task.js:26:7)

```

**Comment by thiagodp** [comment]
@silvoneymachado It appears that the command was produced correctly:
```javascript
I.see("test", "#inputtask2")
```
since Concordia does not know that it is an `input` field.

You can replace 
```gherkin
And I see <#inputtask2> with "test"
```
with
```gherkin
And I see the input <#inputtask2> with "test"
```
and the plug-in should generate the following command:
```javascript
I.seeInField("#inputtask2", "test");
```
Could you please confirm that? Thank you.

**Comment by silvoneymachado** [comment]
Works with `And I see the input <#inputtask2> with "test"`.

Thanks!
